name: "Generate Self-hosted Runner Token"
description: "Generate a token for a self-hosted GitHub Actions runner."
author: "bracketed"

inputs:
  token:
    description: "Authentication token for gh CLI, defaults to the workflow GITHUB_TOKEN."
    required: false
    default: ${{ github.token }}
  org:
    description: "Optional override for the organization name. Defaults to the repository owner."
    required: false
    default: ""

outputs:
  token:
    description: "Registration token for the self-hosted runner"
  expires_at:
    description: "Token expiry timestamp (same as expiresat, provided for compatibility)"

runs:
  using: "composite"
  steps:
    - name: Setup gh
      uses: wusatosi/setup-gh@v1
      with:
        token: ${{ inputs.token }}
        
    - name: Request registration token from the Org
      id: request
      run: |
        set -euo pipefail

        # Determine organization: use input if provided, otherwise repository owner
        if [ -n "${{ inputs.org }}" ]; then
          ORG="${{ inputs.org }}"
        else
          ORG="$GITHUB_REPOSITORY_OWNER"
        fi

        API_PATH="/orgs/${ORG}/actions/runners/registration-token"

        # Make a single POST request (do NOT POST twice — that would create two distinct tokens)
        response="$(gh api --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "$API_PATH" 2>&1)" || {
          echo "gh api request failed:"
          echo "$response"
          exit 1
        }

        # Parse JSON response. jq is available on GitHub-hosted runners.
        token="$(echo "$response" | jq -r '.token // empty')"
        expires_at="$(echo "$response" | jq -r '.expires_at // empty')"

        if [ -z "$token" ]; then
          echo "Failed to extract token from API response:"
          echo "$response"
          exit 1
        fi

        # Provide outputs. Include both 'expiresat' (user requested) and 'expires_at' (API field)
        echo "token=$token" >> "$GITHUB_OUTPUT"
        echo "expires_at=$expires_at" >> "$GITHUB_OUTPUT"
